# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
pandoc_version: 2.7.3
before_install:
  - tlmgr install index

warnings_are_errors: true

os:
  - linux

r:
  - release
  - devTel

r_packages:
  - RTest
  - testthat

install:
  - R -e 'devtools::install_deps(dep = T)'

apt_packages:
  - libxml2-dev
  - libmagick++-dev
