# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
pandoc_version: 2.7.3
before_install:
  - tlmgr install index

warnings_are_errors: true

jobs:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

r:
  - release
  - devel

r_packages:
  - RTest
  - testthat

r_github_packages:
  - jimhester/lintr

apt_packages:
  - libxml2-dev
  - libmagick++-dev

after_success:
  - Rscript -e 'covr::codecov(type = "all")' -e 'lintr::lint_package()'

